/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appAuthenticatedRouteImport } from './routes/(app)/_authenticated'
import { Route as appAuthenticatedIndexRouteImport } from './routes/(app)/_authenticated.index'

const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthenticatedRoute = appAuthenticatedRouteImport.update({
  id: '/(app)/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthenticatedIndexRoute = appAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appAuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/': typeof appAuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/': typeof appAuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_authenticated': typeof appAuthenticatedRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(app)/_authenticated/': typeof appAuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/register' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/'
  id:
    | '__root__'
    | '/(app)/_authenticated'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(app)/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appAuthenticatedRoute: typeof appAuthenticatedRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_authenticated': {
      id: '/(app)/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_authenticated/': {
      id: '/(app)/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appAuthenticatedIndexRouteImport
      parentRoute: typeof appAuthenticatedRoute
    }
  }
}

interface appAuthenticatedRouteChildren {
  appAuthenticatedIndexRoute: typeof appAuthenticatedIndexRoute
}

const appAuthenticatedRouteChildren: appAuthenticatedRouteChildren = {
  appAuthenticatedIndexRoute: appAuthenticatedIndexRoute,
}

const appAuthenticatedRouteWithChildren =
  appAuthenticatedRoute._addFileChildren(appAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appAuthenticatedRoute: appAuthenticatedRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
